# Pipeline configuration for getting form 990PF in xml format
steps:
  # First step for documentation only
  - step_name: load_pdf
    module: custom_operations
    function: convert_pdf_to_images
    process_mode: none    #  "nested", "single", or "none"
    generator:
      enabled: true
      filter: "count < 2"    # filter expression has access to "item" and "count"
    input:
      mode: previous    #  "previous", "storage", or "passthrough"
    output:
      storage:
        type: file    # "memory", "file", or "database"
        format: image_list  # "json", "dataframe", "image_list", or "raw"
        persistence: pipeline  # "step" or "pipeline"
        location: /home/don/Documents/Temp/dev990/data/example.pdf

  # Find urls on gov't website
  - step_name: get_urls
    module: devcontrol.user_level_operations.extract_urls
    function: get_urls_referenced_on_website
    process_mode: single    #  "nested", "single", or "none"
    generator:
      enabled: true
      filter: "count < 2"    # do first element only to start
    input:
      mode: explicit_input
      storage:
        type: url
        value: https://www.irs.gov/charities-non-profits/form-990-series-downloads
    output:
      storage:
        type: memory    # "memory", "file", or "database"
        format: raw  # "json", "dataframe", "image_list", or "raw"
        persistence: pipeline  # "step" or "pipeline"

  # Find urls on gov't website
  - step_name: download_zip_file
    module: devcontrol.user_level_operations.download_zip
    function: download_next_url
    process_mode: single    #  "nested", "single", or "none"
    generator:
      enabled: true       # processes single file, but uses chained generator
      filter: ""
    input:
      mode: previous
    parameters:
      directory: ./output/zip_files
    output:
      storage:
        type: memory    # "memory", "file", or "database"
        format: raw  # "json", "dataframe", "image_list", or "raw"
        persistence: step  # "step" or "pipeline"

  # Unzip downloaded file to directory with name taken from filename
  - step_name: unzip_file
    module: devcontrol.user_level_operations.unzip_file
    function: unzip_driver
    process_mode: single    #  "nested", "single", or "none"
    generator:
      enabled: true       # processes single file, but uses chained generator
      filter: ""
    input:
      mode: previous
    parameters:
      directory: ./output/expanded_zip_files
    output:
      storage:
        type: file    # "memory", "file", or "database"
        format: raw  # "json", "dataframe", "image_list", or "raw"
        location: "/data/zip_files"
        persistence: pipeline  # "step" or "pipeline"

  # Filter downloaded files finding xpath results
  # XPaths can be found in https://github.com/Nonprofit-Open-Data-Collective
  - step_name: filter_files
    module: devcontrol.user_level_operations.filter_files
    function: filter_driver
    process_mode: single    #  "nested", "single", or "none"
    generator:
      enabled: false       # processes single file, but uses chained generator
      filter: ""
    input:
      mode: previous
    parameters:
      directory: ./output/expanded_zip_files/2024_TEOS_XML_02A
      xpaths: ./Xpath990PF.csv
    output:
      storage:
        type: file    # "memory", "file", or "database"
        format: raw  # "json", "dataframe", "image_list", or "raw"
        persistence: pipeline  # "step" or "pipeline"

